openapi: 3.0.1
info:
  title: Star Wars
  description: Star Wars proxy
  version: '1.0'
servers:
  - url: https://red-scus-apimdemo-dev.azure-api.net/sw
paths:
  /people/:
    get:
      summary: Get People
      description: Get People
      operationId: get-people
      responses:
        '200':
          description: ''
  '/people/{id}/':
    get:
      summary: Get People By Id
      description: Get People By Id
      operationId: get-people-by-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: ''
  /film:
    get:
      summary: Get Film
      description: Get Film
      operationId: get-film
      responses:
        '200':
          description: ''
  /*:
    get:
      summary: Wildcard
      description: Wildcard path
      operationId: wildcard
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]