apimServiceName: red-scus-apimdemo-dev
namedValues:
  - name: 66672b71463461136c78195a
    properties:
      displayName: Logger-Credentials--66672b71463461136c78195b
      value: SystemAssigned
  - name: 655686af217d201b1c89ecc2
    properties:
      displayName: Logger-Credentials--655686af217d201b1c89ecc3
      value: "{#appInsightsLoggerKey#}"
  - name: aadb2c-audience
    properties:
      displayName: aadb2c-audience
      value: "{#b2cAudience#}"
  - name: aadb2c-issuer-guid
    properties:
      displayName: aadb2c-issuer-guid
      value: "{#b2cIssuerGuid#}"
  - name: allowed-ip-address
    properties:
      displayName: allowed-ip-address
      value: "{#allowedIPAddress#}"
  - name: AzureOpenAIKey
    properties:
      displayName: AzureOpenAIKey
      value: "{#azureOpenAIKey#}"
  - name: entra-frontend-client-id
    properties:
      displayName: entra-frontend-client-id
      value: "ffb6be58-c386-42f8-81f2-3dc51f9b5d33"
  - name: entraid-backend-audience
    properties:
      displayName: entraid-backend-audience
      value: "{#entraidBackendAudience#}"
  - name: entraid-tenant
    properties:
      displayName: entraid-tenant
      value: "{#entraidTenant#}"
  - name: entraid-tenant-domain
    properties:
      displayName: entraid-tenant-group-allCompany-id
      value: "{#entraidTenantGroupAllCompanyId#}"
  - name: FrontDoorId
    properties:
      displayName: FrontDoorId
      value: "{#frontDoorId#}"
  - name: subscription-id
    properties:
      displayName: subscription-id
      value: "{#subscriptionId#}"
  - name: resource-group-name
    properties:
      displayName: resource-group-name
      value: "{#resourceGroupName#}"
  - name: test
    properties:
      displayName: test
      keyVault: 
        secretIdentifier: https://red-scus-apimdemo-kv.vault.azure.net/secrets/favoritePerson
loggers:
  - name: EventHubLogger1
    properties:
      credentials:
        identityClientId: "{{Logger-Credentials--66672b71463461136c78195b}}"
  - name: brd-scus-apim-ai-dev
    properties:
      loggerType: applicationInsights
      description: App insights logger info
      resourceId: "/subscriptions/{{subscription-id}}/resourceGroups/{{resource-group-name}}/providers/microsoft.insights/components/res-scus-apimdemo-appinsights"
      credentials:
        instrumentationKey: "{{Logger-Credentials--655686af217d201b1c89ecc3}}"
      isBuffered: true
groups:
  - name: 65b3d62ffc4d0a201b6ecb9c
    properties:
      externalId: "{{entraid-tenant-group-allCompany-id}}"
diagnostics:
  - name: applicationinsights
    properties:
      verbosity: Error
      loggerId: "/subscriptions/{{subscription-id}}/resourceGroups/{{resource-group-name}}/providers/Microsoft.ApiManagement/service/res-scus-apimdemo-dev/loggers/brd-scus-apim-ai-dev"
  - name: azuremonitor
    properties:
      loggerId: "/subscriptions/{{subscription-id}}/resourceGroups/{{resource-group-name}}/providers/Microsoft.ApiManagement/service/res-scus-apimdemo-dev/loggers/azuremonitor"
    