#!/bin/bash

# Variables for resource group, location, and APIM instance
RESOURCE_GROUP="yourResourceGroup"
LOCATION="yourLocation"
APIM_NAME="yourApimInstanceName"
SUBSCRIPTION_ID="yourSubscriptionId"
TENANT_ID="yourTenantId"
organizationName="Contoso"
adminEmail="yourEmail@address.com"

# Create the resource group
echo "Creating resource group..."
az group create --name $RESOURCE_GROUP --location $LOCATION

# Create a new APIM instance
echo "Creating APIM instance..."
az apim create --resource-group $RESOURCE_GROUP --name $APIM_NAME --location $LOCATION --publisher-email $adminEmail --publisher-name $organizationName --sku-name "Developer" --sku-capacity 1

# Get the access token using Azure CLI
echo "Getting access token..."
ACCESS_TOKEN=$(az account get-access-token --resource https://management.azure.com/ --query accessToken --output tsv)

# Get the SSO token
echo "Getting SSO token for user name 1 (this should be the admin user)..."
SSO_TOKEN_RESPONSE=$(curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Length:0" -H "Content-Type: application/json" "https://management.azure.com/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.ApiManagement/service/$APIM_NAME/users/1/generateSsoUrl?api-version=2024-06-01-preview")

# Modify the SSO URL to use the developer portal, for some reason the SSO URL generated by the API says portal instead of developer
SSO_URL=$(echo $SSO_TOKEN_RESPONSE | jq -r .value | sed 's/\.portal\./\.developer\./')

# Run the Playwright script using the modified URL
echo "Running Playwright script..."
node ../javascript/playwright-script.js "$SSO_URL"

# Create the portal revision
echo "Creating portal revision..."
curl -X PUT -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" -d '{
  "properties": {
    "description": "Initial revision",
    "isCurrent": true
  }
}' "https://management.azure.com/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.ApiManagement/service/$APIM_NAME/portalRevisions/1?api-version=2024-06-01-preview"