openapi: 3.0.1
info:
  title: Health Check
  description: ''
  version: '1.0'
servers:
  - url: https://brd-scus-apimdemo-dev.azure-api.net/health-check
paths:
  /ping:
    get:
      summary: ping
      description: Always returns a 200
      operationId: ping
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]