openapi: 3.0.1
info:
  title: Http Bin
  description: ''
  version: '1.0'
servers:
  - url: https://red-scus-apimdemo-dev.azure-api.net/httpbin
paths:
  /get:
    get:
      summary: FetchData
      description: FetchData
      operationId: fetchdata
      responses:
        '200':
          description: ''
  '/status/{code}':
    get:
      summary: GetStatus
      description: GetStatus
      operationId: getstatus
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: ''
  /*:
    get:
      summary: WildcardGet
      description: WildcardGet
      operationId: wildcardget
      responses:
        '200':
          description: ''
  /mcp/v1:
    post:
      summary: MCP Post
      description: test
      operationId: mcp-post
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]